# Generated by Django 4.1.1 on 2022-12-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'запрос', 'verbose_name_plural': 'запросы'},
        ),
    ]
