# Generated by Django 4.1.1 on 2022-12-04 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AlterField(
            model_name='request',
            name='content',
            field=models.TextField(blank=True, verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL, verbose_name='заявитель'),
        ),
        migrations.AlterField(
            model_name='request',
            name='leads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('refused', 'отклонено'), ('accepted', 'принято'), ('awaiting', 'ожидание')], default='awaiting', max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=25, verbose_name='название'),
        ),
    ]
