# Generated by Django 4.1.1 on 2022-12-04 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_request_options_alter_request_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='куратор'),
        ),
    ]
