# Generated by Django 4.1.1 on 2022-12-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_request_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
