# Generated by Django 4.1.1 on 2022-12-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_request_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
