# Generated by Django 4.1.1 on 2022-12-19 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('content', models.TextField(blank=True, verbose_name='содержание')),
                ('feedbackCreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackCreatedBy', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
        ),
    ]
