# Generated by Django 4.1.1 on 2022-12-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_request_file_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedbackCreatedBy',
        ),
    ]
